name: ci-workflow

on: [push]

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - run: | 
          echo "Time in GMT ${{steps.hello.outputs.time}}" 
          echo "I live in ${{steps.hello.outputs.town}}" 


