name: Continous Compliance Workflow🔍
on:
  push:
    # branches:
      # - test-continous-compliance
jobs:
  continous-compliance:
    runs-on: ubuntu-latest
    name: A Job that gather compliance evidence and store it in the cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Continous compliance
        uses: redbadger/continous-compliance@v0.4
        id: comply
        with:
          tests-folder: '/test-folder'
      - run: | 
          echo "Show directory contents"
          ls la
          echo "Compliance URL ${{steps.comply.outputs.compliance-evidence-url}}" 