name: Continous Compliance Workflow🔍
on:
  push:
    # branches:
      # - test-continous-compliance
jobs:
  continous-compliance:
    runs-on: ubuntu-latest
    name: A Job that gather compliance evidence and store it in the cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show file contents 
        run: |
          echo "Show directory contents"
          ls -la
      - name: Continous compliance
        uses: redbadger/continous-compliance@v0.6
        id: comply
        with:
          tests-folder: 'test-folder'
          docs-folder: 'doc-folder'
      - run: | 
          echo "Compliance URL ${{steps.comply.outputs.compliance-evidence-url}}" 
          echo "Show directory contents again"
          ls -la
          echo "Go into compliance folder"
          cd compliance
          ls -la
